/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spresto_policeproject_MainActivity */

#ifndef _Included_com_spresto_policeproject_MainActivity
#define _Included_com_spresto_policeproject_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_spresto_policeproject_MainActivity_VERIFY_PERMISSIONS_REQUEST
#define com_spresto_policeproject_MainActivity_VERIFY_PERMISSIONS_REQUEST 1L
#undef com_spresto_policeproject_MainActivity_REQUEST_VIDEO
#define com_spresto_policeproject_MainActivity_REQUEST_VIDEO 1112L
/*
 * Class:     com_spresto_policeproject_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_spresto_policeproject_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
